### PR TITLE
Login page 

### PR DESCRIPTION
**Pull request by pbiradar8**
In the login page of project, the textbox of password should be a secure text entry

### CODE REVIEW

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*

@pbiradar8, thanks for the pull request! It looks like you haven't yet signed the Dropbox CLA. Please [sign it here](https://opensource.dropbox.com/cla/).

**Comment by smarx** [comment]
*Automated message from Dropbox CLA bot*
				
@pbiradar8, thanks for signing the CLA!

**Comment by timabbott** [comment]
Hi @pbiradar8!  Thanks for working on this!  However, this project has been replaced by github.com/zulip/zulip-mobile; apparently we only mentioned this on pages that link to here, and not on this repository.  We'd love to have you contribute there!

**Comment by timabbott** [comment]
Thanks for working on this @pbiradar8!  Closing this, since this project has been replaced by github.com/zulip/zulip-mobile/

**Pull request closed without merging**
